from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

# 1. Individual Clause Analysis (Used by Legal/Financial/Ops Agents)
class ClauseRisk(BaseModel):
    clause_type: str = Field(description="e.g., Liability, Payment, SLA, IP")
    content: str = Field(description="The extracted text of the clause")
    risk_score: int = Field(description="Score from 0-100")
    risk_tag: str = Field(description="e.g., High, Medium, Low")
    recommendation: Optional[str] = Field(description="AI-generated fix")

# 2. Main Contract Object (The "DesignState" equivalent)
class ContractObject(BaseModel):
    # Metadata
    contract_name: str
    counterparty: str
    execution_date: date
    expiry_date: date
    
    summary: str = Field(description="Executive summary generated by the system")
    
    clauses: List[ClauseRisk]
    
    # Aggregated Metrics
    overall_risk_score: int
    legal_risk_score: int
    financial_risk_score: int
    operational_risk_score: int

