from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import date

class ClauseRisk(BaseModel):
    clause_type: str = Field(description="e.g., Liability, Payment, SLA, IP")
    content: str = Field(description="The extracted text of the clause")
    risk_category: str = Field(description="e.g., Legal, Financial, Operational")
    risk_score: int = Field(description="Score from 0-100")
    risk_tag: str = Field(description="e.g., High, Medium, Low")
    recommendation: Optional[str] = Field(description="AI-generated fix")


class ClauseAnalysisResult(BaseModel):
    clauses: List[ClauseRisk] = Field(description="List of analyzed clauses with risk scores")
    overall_risk_score: int = Field(description="Overall contract risk score (0-100)")

class ContractObject(BaseModel):
    # Metadata
    contract_name: str = Field(description="Name of the contract")
    execution_date: date = Field(description="Date the contract was executed")
    expiry_date: date = Field(description="Date the contract expires")
    contract_type: Optional[str] = Field(default="Unknown Contract", description="e.g., MSA, NDA, SOW")
    parties: Optional[List[str]] = Field(default=["Unknown Party"], description="List of all entities involved in the contract")
    governing_law: Optional[str] = Field(default=None, description="Jurisdiction or governing law")
    
    clauses: List[ClauseRisk]
    
    # Aggregated Metrics
    overall_risk_score: int = Field(default=0, description="Overall contract risk score (0-100)")
    legal_risk_score: int = Field(default=0, description="Legal risk score (0-100)")
    financial_risk_score: int = Field(default=0, description="Financial risk score (0-100)")
    operational_risk_score: int = Field(default=0, description="Operational risk score (0-100)")

    summary: str = Field(description="Executive summary generated by the system")


